---
ms.date: 09/13/2016
ms.topic: reference
title: 終了するエラー
description: 終了するエラー
ms.openlocfilehash: b7c9b949a654f10a0421ea69dfe955c8dfb5627e
ms.sourcegitcommit: ba7315a496986451cfc1296b659d73ea2373d3f0
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 12/10/2020
ms.locfileid: "92652546"
---
# <a name="terminating-errors"></a><span data-ttu-id="3b49b-103">終了するエラー</span><span class="sxs-lookup"><span data-stu-id="3b49b-103">Terminating Errors</span></span>

<span data-ttu-id="3b49b-104">このトピックでは、終了エラーを報告するために使用する方法について説明します。</span><span class="sxs-lookup"><span data-stu-id="3b49b-104">This topic discusses the method used to report terminating errors.</span></span> <span data-ttu-id="3b49b-105">また、コマンドレット内からメソッドを呼び出す方法についても説明し、メソッドが呼び出されたときに Windows PowerShell ランタイムによって返される可能性がある例外について説明します。</span><span class="sxs-lookup"><span data-stu-id="3b49b-105">It also discusses how to call the method from within the cmdlet, and it discusses the exceptions that can be returned by the Windows PowerShell runtime when the method is called.</span></span>

<span data-ttu-id="3b49b-106">終了エラーが発生した場合、コマンドレットは [Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) メソッドを呼び出してエラーを報告する必要があります。</span><span class="sxs-lookup"><span data-stu-id="3b49b-106">When a terminating error occurs, the cmdlet should report the error by calling the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method.</span></span> <span data-ttu-id="3b49b-107">このメソッドを使用すると、コマンドレットは、終了エラーの原因となった状態を説明するエラーレコードを送信できます。</span><span class="sxs-lookup"><span data-stu-id="3b49b-107">This method allows the cmdlet to send an error record that describes the condition that caused the terminating error.</span></span> <span data-ttu-id="3b49b-108">エラーレコードの詳細については、「 [Windows PowerShell エラーレコード](./windows-powershell-error-records.md)」を参照してください。</span><span class="sxs-lookup"><span data-stu-id="3b49b-108">For more information about error records, see [Windows PowerShell Error Records](./windows-powershell-error-records.md).</span></span>

<span data-ttu-id="3b49b-109">[Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)メソッドが呼び出されると、Windows PowerShell ランタイムによって、パイプラインの実行が完全に停止され、 [Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException)例外がスローされてしまいます。</span><span class="sxs-lookup"><span data-stu-id="3b49b-109">When the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method is called, the  Windows PowerShell runtime permanently stops the execution of the pipeline and throws a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span> <span data-ttu-id="3b49b-110">その後、 [WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject)、 [WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)、またはその他のいくつかの api を呼び出そうとすると、これらの呼び出しによって [Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) 例外がスローされることになります。</span><span class="sxs-lookup"><span data-stu-id="3b49b-110">Any subsequent attempts to call [System.Management.Automation.Cmdlet.WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError), or several other APIs causes those calls to throw a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span>

<span data-ttu-id="3b49b-111">また、 [Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) 例外は、パイプラインの別のコマンドレットが終了エラーを報告した場合、ユーザーがパイプラインの停止を要求した場合、または何らかの理由で完了前にパイプラインが停止した場合にも発生することがあります。</span><span class="sxs-lookup"><span data-stu-id="3b49b-111">The [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception can also occur if another cmdlet in the pipeline reports a terminating error, if the user has asked to stop the pipeline, or if the pipeline has been halted before completion for any reason.</span></span> <span data-ttu-id="3b49b-112">このコマンドレットは、開いているリソースまたはその内部状態をクリーンアップする必要がない限り、 [Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) 例外をキャッチする必要はありません。</span><span class="sxs-lookup"><span data-stu-id="3b49b-112">The cmdlet does not need to catch the [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception unless it must clean up open resources or its internal state.</span></span>

<span data-ttu-id="3b49b-113">コマンドレットは、終了エラーを報告する前に、任意の数の出力オブジェクトまたは終了しないエラーを書き込むことができます。</span><span class="sxs-lookup"><span data-stu-id="3b49b-113">Cmdlets can write any number of output objects or non-terminating errors before reporting a terminating error.</span></span> <span data-ttu-id="3b49b-114">ただし、終了エラーによってパイプラインが完全に停止されます。これ以降の出力、終了エラー、または終了しないエラーは報告されません。</span><span class="sxs-lookup"><span data-stu-id="3b49b-114">However, the terminating error permanently stops the pipeline, and no further output, terminating errors, or non-terminating errors can be reported.</span></span>

<span data-ttu-id="3b49b-115">コマンドレットで[Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)を呼び出すことができるのは、[システム](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)の呼び出しを実行したスレッド、また[は、また](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)[はシステムを](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)使用して、..................................... コマンド処理メソッド</span><span class="sxs-lookup"><span data-stu-id="3b49b-115">Cmdlets can call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) only from the thread that called the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) input processing method.</span></span> <span data-ttu-id="3b49b-116">別のスレッドから [Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) または [WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) を呼び出すことはできませんが、このような処理は行われません。</span><span class="sxs-lookup"><span data-stu-id="3b49b-116">Do not attempt to call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) or [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) from another thread.</span></span> <span data-ttu-id="3b49b-117">代わりに、エラーをメインスレッドに送り返す必要があります。</span><span class="sxs-lookup"><span data-stu-id="3b49b-117">Instead, errors must be communicated back to the main thread.</span></span>

<span data-ttu-id="3b49b-118">コマンドレット[が、](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)[システム](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)の実装で例外をスローする可能性があります。...................................................... コマンド[レット。](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)</span><span class="sxs-lookup"><span data-stu-id="3b49b-118">It is possible for a cmdlet to throw an exception in its implementation of the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) method.</span></span> <span data-ttu-id="3b49b-119">これらのメソッドからスローされた例外 (Windows PowerShell ホストを停止するいくつかの重大なエラー状態を除く) は、Windows PowerShell 全体ではなく、パイプラインを停止する終了エラーとして解釈されます。</span><span class="sxs-lookup"><span data-stu-id="3b49b-119">Any exception thrown from these methods (except for a few severe error conditions that stop the Windows PowerShell host) is interpreted as a terminating error which stops the pipeline, but not Windows PowerShell as a whole.</span></span> <span data-ttu-id="3b49b-120">(これは、メインコマンドレットスレッドにのみ適用されます。</span><span class="sxs-lookup"><span data-stu-id="3b49b-120">(This applies only to the main cmdlet thread.</span></span> <span data-ttu-id="3b49b-121">一般に、コマンドレットによって生成されるスレッドでキャッチされない例外は、Windows PowerShell ホストを停止します)。エラーレコードには、エンドユーザーに役立つエラー状態に関する追加情報が記載されているので、例外をスローするのではなく、 [Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) を使用することをお勧めします。</span><span class="sxs-lookup"><span data-stu-id="3b49b-121">Uncaught exceptions in threads spawned by the cmdlet, in general, halt the Windows PowerShell host.) We recommend that you use [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) rather than throwing an exception because the error record provides additional information about the error condition, which is useful to the end-user.</span></span> <span data-ttu-id="3b49b-122">コマンドレットは、すべての例外のキャッチと処理 () に対してマネージコードのガイドラインに従う必要があり `catch (Exception e)` ます。</span><span class="sxs-lookup"><span data-stu-id="3b49b-122">Cmdlets should honor the managed code guideline against catching and handling all exceptions (`catch (Exception e)`).</span></span> <span data-ttu-id="3b49b-123">既知の型と予期される型の例外のみをエラーレコードに変換します。</span><span class="sxs-lookup"><span data-stu-id="3b49b-123">Convert only exceptions of known and expected types into error records.</span></span>

## <a name="see-also"></a><span data-ttu-id="3b49b-124">参照</span><span class="sxs-lookup"><span data-stu-id="3b49b-124">See Also</span></span>

[<span data-ttu-id="3b49b-125">システムの管理... コマンドレット</span><span class="sxs-lookup"><span data-stu-id="3b49b-125">System.Management.Automation.Cmdlet.BeginProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)

[<span data-ttu-id="3b49b-126">システムの管理... コマンドレット</span><span class="sxs-lookup"><span data-stu-id="3b49b-126">System.Management.Automation.Cmdlet.EndProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)

[<span data-ttu-id="3b49b-127">システムの管理....................</span><span class="sxs-lookup"><span data-stu-id="3b49b-127">System.Management.Automation.Cmdlet.ProcessRecord</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)

[<span data-ttu-id="3b49b-128">Pipelinestoppedexception (システム管理)</span><span class="sxs-lookup"><span data-stu-id="3b49b-128">System.Management.Automation.Pipelinestoppedexception</span></span>](/dotnet/api/System.Management.Automation.PipelineStoppedException)

[<span data-ttu-id="3b49b-129">Throwterminatingerror \* のようになります。</span><span class="sxs-lookup"><span data-stu-id="3b49b-129">System.Management.Automation.Cmdlet.Throwterminatingerror\*</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)

[<span data-ttu-id="3b49b-130">WriteError (システム管理)</span><span class="sxs-lookup"><span data-stu-id="3b49b-130">System.Management.Automation.Cmdlet.WriteError</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)

[<span data-ttu-id="3b49b-131">Windows PowerShell エラー レコード</span><span class="sxs-lookup"><span data-stu-id="3b49b-131">Windows PowerShell Error Records</span></span>](./windows-powershell-error-records.md)

[<span data-ttu-id="3b49b-132">Windows PowerShell コマンドレットの記述</span><span class="sxs-lookup"><span data-stu-id="3b49b-132">Writing a Windows PowerShell Cmdlet</span></span>](./writing-a-windows-powershell-cmdlet.md)
